src/sonic_ax_impl/bin/sysDescr_pass.py
Use a snmp-specific location instead of historical shared location
=> Modify sysDescription file location

src/sonic_ax_impl/mibs/__init__.py, src/sonic_ax_impl/mibs/ietf/rfc1213.py, src/sonic_ax_impl/mibs/ietf/rfc2863.py
- Add port channels support to RFC1213 (1.3.6.1.2.1.2) and
RFC2863 (1.3.6.1.2.1.31.1) MIBs.
- Read oper state, admin state and MTU value from DB.
=> [sonic_ax_impl]: Add support of port channels.

src/ax_interface/mib.py, src/sonic_ax_impl/mibs/__init__.py, src/sonic_ax_impl/mibs/ieee802_1ab.py, src/sonic_ax_impl/mibs/ietf/rfc1213.py, src/sonic_ax_impl/mibs/ietf/rfc2863.py, src/sonic_ax_impl/mibs/ietf/rfc4292.py, src/sonic_ax_impl/mibs/ietf/rfc4363.py
1. Refactor database connections utility
2. Add reinit_data method into mib.py. This optional method is run every minute
Previously interface list was initialized just when snmpagent starts. Now it would be reinitialized every 60 seconds.
=> [SNMP Counters]: Update interface list periodically

src/sonic_ax_impl/mibs/ietf/rfc4292.py, src/sonic_ax_impl/mibs/ietf/rfc4363.py, tests/test_forward.py
TODO: The final fix should be inside the library, let it returns empty list when there is no keys matching the pattern
=> Fix: temporarily fix DBConnector keys return none instead of empty list

src/sonic_ax_impl/mibs/ietf/rfc4292.py
Following https://github.com/Azure/sonic-snmpagent/pull/29, fix a syntax bug.
=> Exclude non front panel interfaces from nexthop

src/ax_interface/mib.py
Sample syslog for a flawed updater:
```
Jun  9 06:53:25.0 str-s6000-on-5 ERR snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception#012Traceback (most recent call last):#012
File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 45, in start#012    self.update_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ietf/rfc4292.py", line 38, in update_data#012    for route_entry in route_entries:#012TypeError: 'NoneType' object is not iterable
```
=> Add logging for updaters and MIBTable background task

src/ax_interface/mib.py, tests/test_forward.py, tests/test_hc_interfaces.py, tests/test_interfaces.py
There is a bug if query a SubtreeMIBEntry with a short OID, it will not
return the first element in the subtree. For example:
```
$ snmpwalk -v2c -c <secret> <ip> 1.3.6.1.2.1.4.24.4.1.1
iso.3.6.1.2.1.4.24.4.1.1.0.0.0.0.0.0.0.0.0.10.0.0.1 = IpAddress: 0.0.0.0
iso.3.6.1.2.1.4.24.4.1.1.0.0.0.0.0.0.0.0.0.10.0.0.3 = IpAddress: 0.0.0.0
iso.3.6.1.2.1.4.24.4.1.1.0.0.0.0.0.0.0.0.0.10.0.0.5 = IpAddress: 0.0.0.0
iso.3.6.1.2.1.4.24.4.1.1.0.0.0.0.0.0.0.0.0.10.0.0.7 = IpAddress: 0.0.0.0
iso.3.6.1.2.1.4.24.4.1.1.0.0.0.0.0.0.0.0.0.10.0.0.9 = IpAddress: 0.0.0.0
iso.3.6.1.2.1.4.24.4.1.1.0.0.0.0.0.0.0.0.0.10.0.0.11 = IpAddress: 0.0.0.0
iso.3.6.1.2.1.4.24.4.1.1.0.0.0.0.0.0.0.0.0.10.0.0.13 = IpAddress: 0.0.0.0
iso.3.6.1.2.1.4.24.4.1.1.0.0.0.0.0.0.0.0.0.10.0.0.15 = IpAddress: 0.0.0.0 …
```
=> Fix SubtreeMIBEntry iter(). Fix all unit tests

src/sonic_ax_impl/mibs/__init__.py, tests/mock_tables/appl_db.json, tests/test_mibs.py
1. Fix init_sync_d_lag_tables(): supports empty LAG member
2. Fix init_sync_d_lag_tables(): if_name_lag_name_map behaves as comments
3. Add test case for LAG interfaces
=> Fix empty lag members, fix if_name_lag_name_map

src/sonic_ax_impl/mibs/ieee802_1ab.py, tests/test_lldp.py
Fix the bug: if any port has no neighbor, lldpMIB will have no response.
=> Fix lldpMIB: use SubtreeMIBEntry

src/ax_interface/__init__.py, src/ax_interface/mib.py, src/sonic_ax_impl/mibs/ieee802_1ab.py, src/sonic_ax_impl/mibs/ietf/rfc1213.py, src/sonic_ax_impl/mibs/ietf/rfc2863.py, src/sonic_ax_impl/mibs/ietf/rfc4292.py, src/sonic_ax_impl/mibs/ietf/rfc4363.py, tests/test_arp.py, tests/test_forward.py, tests/test_hc_interfaces.py
Originally some updaters wait for COUNTERS_PORT_NAME_MAP and/or other critical data structures in redis in ctor. If syncd does things slowly, the waiting will timeout, and crash the subagent process.
This pull request make the updater ctor quite safe, ie. no throw at all. And any future updating exceptions are already handled well by the class MIBTable.
Tested rebooting in lab, with a small wait timeout.
=> Make MIBUpdater classes ctor no throw

src/sonic_ax_impl/mibs/ietf/rfc4363.py
API reference : https://github.com/Azure/sonic-py-swsssdk/pull/30
=> Get Vlan Id from ASIC_STATE Vlan Object if bvid present

src/sonic_ax_impl/mibs/ieee802_1ab.py
```
Nov 29 00:05:31.275681 str-s6100-acs-2 WARNING snmp-subagent [sonic_ax_impl] WARNING: 0 - b'LLDP_ENTRY_TABLE' is empty. No LLDP information could be retrieved.
Nov 29 00:05:38.297445 str-s6100-acs-2 WARNING snmp-subagent [sonic_ax_impl] WARNING: 0 - b'LLDP_ENTRY_TABLE' is empty. No LLDP information could be retrieved.
Nov 29 00:05:43.314568 str-s6100-acs-2 WARNING snmp-subagent [sonic_ax_impl] WARNING: 0 - b'LLDP_ENTRY_TABLE' is empty. No LLDP information could be retrieved.
Nov 29 00:05:46.330162 str-s6100-acs-2 WARNING snmp-subagent [sonic_ax_impl] WARNING: 0 - b'LLDP_ENTRY_TABLE' is empty. No LLDP information could be retrieved.
Nov 29 00:05:50.346836 str-s6100-acs-2 WARNING snmp-subagent [sonic_ax_impl] WARNING: 0 - b'LLDP_ENTRY_TABLE' is empty. No LLDP information could be …
```
=> [ieee802_1ab]: This message is not needed as the device could be isolated

src/sonic_ax_impl/mibs/ieee802_1ab.py, tests/mock_tables/dbconnector.py
Add mock pubsub, so unittests can properly test MIBs with updaters that use keyspace notifications.
Also fix/enhance lldp MIBs.
=> Fix/enhance lldp MIBs., add MockPubSub to mock_tables.dbconnector.py

src/sonic_ax_impl/mibs/ietf/rfc1213.py, src/sonic_ax_impl/mibs/ietf/rfc2863.py, tests/mock_tables/appl_db.json, tests/test_hc_interfaces.py, tests/test_interfaces.py
* ifSpeed now reports speed under 2^32 bps
* ifSpeed returns 2^32 is speed is above
* ifHighSpeed reports the interface speed in Mbps
* ifHighSpeed defaults to 40000 if speed not available in APPL_DB
* unit tests for rfc1213 and rfc2863
* appl_db.json modified to provide variety of speeds
Signed-off-by: michel.moriniaux@gmail.com
After building code I saw that there was already a pull request for this feature. As there was no activity since February on it, my pull has unit tests and more completeness I went ahead with this one.
=> sonic-snmpagent: fixed interface speeds

src/sonic_ax_impl/mibs/ieee802_1ab.py, tests/test_lldp.py
I noticed that for some LLDP MIB tables the indexes are not correct according to specification.
For example lets consider lldpRemTable:
```
lldpRemEntry OBJECT-TYPE
SYNTAX      LldpRemEntry
. . .
INDEX   {
lldpRemTimeMark,
lldpRemLocalPortNum,
lldpRemIndex
}
::= { lldpRemTable 1 }
```
This means that we have some meaningful sub oids when doing snmpwalk:
```
snmpwalk  -v1  -cpublic arc-switch1041  1.0.8802.1.1.2.1.4.1
iso.0.8802.1.1.2.1.4.1.1.1.61552.85.25 = Timeticks: (61552) 0:10:15.52
. . . 
```
iso.0.8802.1.1.2.1.4.1 - lldpRemTable
.1 -  lldpRemEntry
.1 - lldpRemTimeMark
.61552 - lldpRemTimeMark (index )
.85 - lldpRemLocalPortNum (index )
.25 - lldpRemIndex (index)
Example snmpwalk output:
Previously we had:
```
snmpwalk  -v2c  -cpublic arc-switch1038 …
```
=> [lldp] LLDP-MIB indexes according to specification

src/sonic_ax_impl/__init__.py, src/sonic_ax_impl/mibs/__init__.py, tests/mock_tables/appl_db.json, tests/test_lldp.py, tests/test_sn.py
This file was added long time ago and now it is not needed anymore.
We can simply get port aliases from DB.
This also means that aliases will be now updated from DB once
a reinit timeout, instead of beeing static in alias_map.json
Signed-off-by: Stepan Blyschak <stepanb@mellanox.com>
I removed alias_map.json from SNMP agent. That map is not needed anymore since we can get port alias directly from DB
1. Removed /etc/snmp/alias_map.json parsing
2. Generate ```if_alias_map``` using aliases from APPL_DB
3. Added aliases in test appl_db.json table and fixed tests, that were expecting that alias == ifname
Run unittests, run snmp agent on DUT and verify that we can still see correct aliases in SNMP MIBs
**- Description for the …
=> Remove alias_map.json

src/sonic_ax_impl/mibs/__init__.py, src/sonic_ax_impl/mibs/ieee802_1ab.py, src/sonic_ax_impl/mibs/ietf/rfc1213.py, src/sonic_ax_impl/mibs/ietf/rfc2863.py, tests/mock_tables/appl_db.json, tests/mock_tables/config_db.json, tests/mock_tables/dbconnector.py, tests/mock_tables/state_db.json, tests/test_hc_interfaces.py, tests/test_interfaces.py, tests/test_lldp.py
Design doc: https://github.com/Azure/SONiC/wiki/SONiC-SMMP-Design-on-Management-Ports
Add management port support to Interface/LLDP MIBs
Implement this by getting management port info from MGMT_PORT_TABLE from APPL DB
Insert some fake entries into MGMT_PORT_TABLE and make verify they are present in above MIBs
Add managment port support to RFC1213, RFC2863, IEEE802.1ab MIBs
=> Add managment port support to RFC1213, RFC2863, IEEE802.1ab MIBs

src/sonic_ax_impl/mibs/ieee802_1ab.py
Return empty string if port description is not present in DB
Management port doesn't have description in DB so return empty instead of returning None
Signed-off-by: Stepan Blyschak <stepanb@mellanox.com>
=> Fix LLDP local port description field

src/sonic_ax_impl/mibs/ietf/rfc1213.py, src/sonic_ax_impl/mibs/ietf/rfc2863.py
This is too verbose for syslog. Since we have TODO comment, safe to remove.
=> Remove verbose feature missing logs

setup.cfg, setup.py
Signed-off-by: Sangita Maity samaity@linkedin.com
- **What I did**
Integrate py.test into setuptools as vanilla 'python3 setup.py test' does not work.
This PR is needed for snmp stretch upgrade docker PR.
1. [https://github.com/Azure/sonic-buildimage/pull/2620](https://github.com/Azure/sonic-buildimage/pull/2620)
- **How to verify it**
Use this PR with snmp docker upgrade PR in sonic-buildimage.
Ref: https://docs.pytest.org/en/latest/goodpractices.html
=> integrating py.test into setuptools

src/sonic_ax_impl/mibs/ieee802_1ab.py, tests/mock_tables/appl_db.json
1.0.8802.1.1.2.1.3.8 | lldpLocManAddrTable
-- | --
fixes #104 
>According source code, 
The mgmt_ip_bytes is got from the lldp_loc_man_addr field of LLDP_LOC_CHASSIS table in APPL_DB
The content of decoded mgmt_ip_str string will be "[u'240.127.1.1', u'fe80::ce37:abff:feec:de9c']".
To specify the separator '.' to split the mgmt_ip_str, will get ValueError: invalid literal for int() with base 10: "[u'240".
The mgmt_ip_str string can' t just decoded from mgmt_ip_bytes, shall filter some characters, e.g., u and '.
>snmpwalk -v2c -c public 192.168.1.100 1.0.8802.1.1.2.1.3.8
iso.0.8802.1.1.2.1.3.8.1.1.1.4.10.1.0.1 = INTEGER: 1
iso.0.8802.1.1.2.1.3.8.1.3.1.4.10.1.0.1 = INTEGER: 5
iso.0.8802.1.1.2.1.3.8.1.4.1.4.10.1.0.1 = INTEGER: 2 …
=> Fix issue #104: lldpLocManAddrTable supports multiple IP addresses

tests/test_hc_interfaces.py
Added MGMT port speed tests to verify the value exposed by SNMP
By adding the test to test_hc_interfaces.py
Run the tests to verify that it passes
=> Add mgmt port speed test 

README.md, src/sonic_ax_impl/__main__.py
[sonic_ax_impl/__main__.py]: Add signal handler to change debug level.    
Today, We can not alter the log level of already running snmp-subagent.
Adding a signal handler for signal SIGUSR1 to switch log level for both
sonic_ax_impl and ax_interface logger.
Signed-off-by: Praveen Chaudhary <pchaudhary@linkedin.com>
Today, We can not alter the log level of already running snmp-subagent.
Adding a signal handler for signal SIGUSR1 to switch log level for both
sonic_ax_impl and ax_interface logger.
Using Signal Handler. Same thing can be done using socket or a thread looking for some config/file but that eats more resources unnecessarily.
admin@lnos-x1-a-csw04:~$ sudo service snmp restart <<<< [restart with latest code] …
=> [sonic_ax_impl/__main__.py]: Add signal handler to change debug level.

src/sonic_ax_impl/mibs/__init__.py, src/sonic_ax_impl/mibs/ieee802_1ab.py
In some use cases, the ConfigDB has no management ports at all. Then we see verbose warnings in syslog:
```
Oct  7 23:52:37.279295 sonic WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: No managment ports found in b'MGMT_PORT|'
Oct  7 23:52:50.186946 sonic WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: No managment ports found in b'MGMT_PORT|'
Oct  7 23:52:52.895705 sonic WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: No managment ports found in b'MGMT_PORT|'
Oct  7 23:52:56.769412 sonic WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: No managment ports found in b'MGMT_PORT|'
Oct  7 23:52:56.769507 sonic WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: Invalid mgmt IP
Oct  7 23:52:56.770222 sonic WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: …
```
=> Reduce syslog warnings when ConfigDB has no management ports

src/sonic_ax_impl/mibs/ieee802_1ab.py, src/sonic_ax_impl/mibs/ietf/rfc2737.py
* application should use get api to obtain dbid instead of accessing internal variable  
* later for multi DB changes, we will redesign the internal db_map variable and implementation of get_dbid API , so to avoid breakage, we should use API to obtain dbid and merge snmpagent first.
Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com
=> Using get API to obtain dbid instead of internal var directly

src/sonic_ax_impl/mibs/ieee802_1ab.py, tests/mock_tables/appl_db.json, tests/test_lldp.py
Fix system capabilities parsing issue.
For lldp_rem_sys_cap_supported, lldp_rem_sys_cap_enabled, lldp_loc_sys_cap_supported, and lldp_loc_sys_cap_enabled objects,
shall converts string to hex bytes.
Before modified
> 
D:\TOOL\snmp>snmpwalk -v2c -c public 192.168.1.100  1.0.8802.1.1.2.1.3
iso.0.8802.1.1.2.1.3.1 = INTEGER: 4
iso.0.8802.1.1.2.1.3.2 = STRING: "cc:37:ab:ec:de:9c"
iso.0.8802.1.1.2.1.3.3 = STRING: "sonic"
iso.0.8802.1.1.2.1.3.4 = STRING: "Debian GNU/Linux 9 (stretch) Linux 4.9.0-9-2-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2015-12-19) x86_64"
iso.0.8802.1.1.2.1.3.5 = STRING: "28 00"                         ==> error
iso.0.8802.1.1.2.1.3.6 = STRING: "28 00"                          ==> error
D:\TOOL\snmp>snmpwalk -v2c -c …
=> Fix system capabilities parsing issue.

src/sonic_ax_impl/mibs/ietf/rfc1213.py, tests/mock_tables/config_db.json, tests/test_interfaces.py
Fix bug: if one mgmt port does not exist in StateDB, treat the oper/admin status as unknown.
Currently it will throw exception:
```
ERROR:ax_interface:SubtreeMIBEntry.__call__() caught an unexpected exception during _callable_.__call__()
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 196, in __call__
return self._callable_.__call__(sub_id, *self._callable_args)
File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ietf/rfc1213.py", line 381, in get_oper_status
return self._get_status(sub_id, b"oper_status")
File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ietf/rfc1213.py", line 357, in _get_status
entry = self._get_if_entry_state_db(sub_id)
File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ie …
```
=> Fix bug: if one mgmt port does not exist in StateDB, treat the oper/admin status as unknown

src/sonic_ax_impl/mibs/ieee802_1ab.py, tests/test_lldp.py
Ensure `not-accessible` nodes (index nodes in MIB table) in tables in LLDP MIB are not readable by SNMP get operation.
Remove the code which processes read request of index nodes and their access right (`MAX-ACCESS` caluse) are `not-accessible`:
* Index node `lldpLocPortNum` in `lldpLocPortTable`,
* Index nodes `lldpLocManAddrSubtype` and `lldpLocManAddr` in `lldpLocManAddrTable`,
* Index nodes `lldpRemTimeMark`, `lldpRemLocalPortNum` and `lldpRemIndex` in `lldpRemTable`, and
* Index nodes `lldpRemManAddrSubtype` and `lldpRemManAddr` in `lldpRemManAddrTable` tables
Before modified
iso.0.8802.1.1.2.1.3.7.1.1.1 = INTEGER: 1
iso.0.8802.1.1.2.1.3.7.1.1.5 = INTEGER: 5
iso.0.8802.1.1.2.1.3.7.1.1.9 = INTEGER: 9 …
=> Fix index nodes in LLDP tables whose access right is not-accessible.

src/sonic_ax_impl/lib/quaggaclient.py, tests/mock_tables/bgpsummary_ipv6_nobgp.txt, tests/test_vtysh.py
If there is no ipv4 or ipv6 BGP neighbors configured, the messages are a little different in different Quagga/FRR version.
Quagga in 201811
```
sonic> show ipv6 bgp su
No IPv6 neighbor is configured
sonic> 
```
FRR in 201811
```
sonic> show ip bgp ipv6 summary
sonic>
```
FRR in master
```
sonic> show ip bgp ipv6 summary
% No BGP neighbors found
sonic> 
```
Currently we could not handle 2nd or 3rd cases.
=> Fix Quagga/FRR parser on IPv6 BGP sessions

src/ax_interface/mib.py
As part of converting the snmp docker to buster, I observed that the snmp subagent exits after throwing an exception.
```
May  5 21:35:16.852142 sonic ERR snmp#snmp-subagent [sonic_ax_impl] ERROR: Uncaught exception in sonic_ax_impl.main#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/main.py", line 70, in main#012    event_loop.run_until_complete(agent.run_in_event_loop())#012  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete#012    return future.result()#012  File "/usr/local/lib/python3.7/dist-packages/ax_interface/agent.py", line 37, in run_in_event_loop#012    background_task = self.mib_table.start_background_tasks(self.oid_updaters_enabled)#012  File …
```
=> Fix exception when running snmp subagent under python3.7

src/sonic_ax_impl/mibs/__init__.py, tests/test_mibs.py
Signed-off-by: SuvarnaMeenakshi <sumeenak@microsoft.com>
To support namespaces, we added a Namespace class with functions to support getting data from all databases.
The Namespace dbs_get_all function , checks if the key exists in the database and does db connect before executing get_all.
Both of this operation causes additional time, which was causing agentx socket to disconnect.
- Remove the additional check that was added to see if the key exists before doing a get all.
- Remove db connect from dbs_get_all , as this was adding additional delay in dbs_get_all function, which is called during update_data. Instead, connect to all dbs during initialization, and connect to required dbs before invoking sync_d functions to ensure connection persists …
=> [Namespace]: Fix SNMP AgentX  socket connection timeout when using Namespace.get_all() 

src/sonic_ax_impl/mibs/__init__.py
Fix LGTM alert reported by PR https://github.com/Azure/sonic-snmpagent/pull/141 because of missing @staticmethod decorator.
=> Fix LGTM reported alert of PR#141

src/sonic_ax_impl/mibs/ietf/rfc2737.py, tests/mock_tables/asic0/state_db.json, tests/mock_tables/asic1/state_db.json, tests/mock_tables/state_db.json
Update transceiver info DB key names to align with recent change here: https://github.com/Azure/sonic-platform-common/pull/97
=> Update transceiver info DB key names

src/sonic_ax_impl/mibs/ietf/rfc1213.py, tests/namespace/test_interfaces.py
Signed-off-by: SuvarnaMeenakshi <sumeenak@microsoft.com>
In multi-asic platform, SAI OID is not unique for the whole device. It is unique for an asic and within a single namespace.
This PR is to fix InterfacesMIB rfc1213 implementation to make sure that interfaces counters is keyed based on interface index and not SAI OID.
In rfc1213 ; update code to use interface index as key in interface counter dict.
Run unit-test for namespace as well.
Verified on multi-asic and single asic platform, to check interface counters are correct.
=> [201911] Fix interface counters in RFC1213

src/sonic_ax_impl/mibs/ieee802_1ab.py
LLDPRemTableUpdater index in OID is a tuple of  (remote time mark, if index, remote device index).
```
For example: LLDP-MIB::lldpRemSysName.615.177.11 = STRING: remote_device_name
here , remote time mark is 615, interface index is 615, remote device index is 11.
```
In case of multi-asic platform, when querying this MIB it can happen that same if index result is seen in SNMP walk, with a different remote time mark. 
```
For example: 
LLDP-MIB::lldpRemSysName.615.177.11 = STRING: remote_device_name
LLDP-MIB::lldpRemSysName.625.177.11 = STRING: remote_device_name
```
In the above walk, 177 interface index data appears twice.
To avoid showing same if index result in the  result, set remote time mark to 0, as this value is not significant, 
**- How to …
=> [LLDP]: Modify OID index of LLDPRemTableUpdater MIB

src/sonic_ax_impl/mibs/__init__.py, src/sonic_ax_impl/mibs/ieee802_1ab.py, src/sonic_ax_impl/mibs/ietf/rfc1213.py, src/sonic_ax_impl/mibs/ietf/rfc2737.py, src/sonic_ax_impl/mibs/ietf/rfc2863.py, src/sonic_ax_impl/mibs/ietf/rfc4363.py, src/sonic_ax_impl/mibs/vendor/cisco/ciscoPfcExtMIB.py, src/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py, tests/namespace/test_mibs.py, tests/test_mibs.py
functions.
Signed-off-by: SuvarnaMeenakshi <sumeenak@microsoft.com>
Namespace class was added to support getting data from multiple namespaces.
This class includes some functions which get data from multiple namespaces and combine them.
This PR is to simplify the function of getting from separate functions and merge them.
Write a higher order function to invoke individual function to retrieve data from a single namespace.
The higher order function will retrieve the data and combine.
No change in single and multi-asic snmp walk outputs.
Only implementation changes.
Make sure snmp walk outputs before change and after change are the same.
=> [Namespace]: Simplify sync_d functions to use higher order

pytest.ini, setup.py
Add coverage for source code.
```
----------- coverage: platform linux, python 3.7.3-final-0 -----------
Name                                                              Stmts   Miss  Cover
-------------------------------------------------------------------------------------
src/ax_interface/__init__.py                                          8      0   100%
src/ax_interface/agent.py                                            28     20    29%
src/ax_interface/constants.py                                        47      0   100%
src/ax_interface/encodings.py                                       136     12    91%
src/ax_interface/exceptions.py                                       26      7    73%
src/ax_interface/mib.py …
```
=> [pytest/coverage]: add coverage support

setup.py
Add 'wheel' to the list of packages required for building the package. This way it will be implicitly installed at build time, preventing the need to intstall the 'wheel' package explicitly in our build environment.
=> [setup.py] Add 'wheel' package to 'setup_requires' list

src/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py
[ciscoSwitchQosMIB]: Remove invocation of update_data function in reinit_data
function. udpate_data and reinit_data will be invoked by periodic
events. update_data need not be invoked by reinit_data again.
Additional invocation of update_data can cause increase in running time
on multi-asic platform causing Agentx socket connection to break.
Signed-off-by: SuvarnaMeenakshi <sumeenak@microsoft.com>
Removed invocation of update_data function in reinit_data function. 
udpate_data and reinit_data will be invoked by periodic events. 
update_data need not be invoked by reinit_data again.
Additional invocation of update_data can cause increase in running time on multi-asic platform causing Agentx socket connection to break.
Remove update_data call in …
=> [ciscoSwitchQosMIB]: Remove invocation of update_data function in reinit_data

src/sonic_ax_impl/mibs/ieee802_1ab.py, tests/namespace/test_lldp.py, tests/test_lldp.py
Fixed https://github.com/Azure/sonic-snmpagent/issues/163
=> Fix: correctly handle that lldp_loc_man_addr contains only IPv6 address without IPv4 address

src/sonic_ax_impl/mibs/__init__.py, tests/mock_tables/asic0/appl_db.json, tests/mock_tables/asic1/appl_db.json, tests/mock_tables/asic2/appl_db.json, tests/mock_tables/dbconnector.py, tests/mock_tables/global_db/appl_db.json, tests/namespace/test_lldp.py, tests/test_lldp.py
[LLDP]: Update init_db to load global database config 
before initializing SonicV2Connector class.
LLDPLocManAddrUpdater requires information from host database hence uses init_db() to initialize the host db.
For unit-testing multi-asic code path, there are mock db files provided for global_db and namespace specific dbs.
As init_db did not load global database config, unit-test mock db was not loading global_db database files for LLDPLocManAddrUpdater unit-testing. Fixed this by loading global database config in init_db function.
As init_db did not load global database config, unit-test mock db was not loading global_db database files for LLDPLocManAddrUpdater unit-testing. Fixed this by loading global database config in init_db function.
- Load global …
=> [LLDP]: Update init_db to load global database config

tests/mock_tables/asic0/appl_db.json, tests/mock_tables/asic1/appl_db.json, tests/mock_tables/asic2/appl_db.json, tests/mock_tables/global_db/appl_db.json, tests/namespace/test_lldp.py
Then fixed https://github.com/Azure/sonic-snmpagent/issues/165
=> Add a test case for LLDP_LOC_CHASSIS.lldp_loc_man_addr has only one IPv6 address

src/sonic_ax_impl/mibs/ietf/rfc4292.py, tests/mock_tables/asic0/config_db.json, tests/mock_tables/asic1/config_db.json, tests/mock_tables/asic2/appl_db.json, tests/mock_tables/asic2/config_db.json, tests/mock_tables/dbconnector.py, tests/mock_tables/multi_asic.py, tests/namespace/test_forward.py, tests/test_forward.py
=> [RFC4292][Namespace][201911]: Fix implementation of RouteUpdater for multi-asic platform

src/sonic_ax_impl/mibs/ietf/rfc4292.py, tests/mock_tables/asic0/config_db.json, tests/mock_tables/asic1/config_db.json, tests/mock_tables/asic2/appl_db.json, tests/mock_tables/asic2/config_db.json, tests/mock_tables/dbconnector.py, tests/mock_tables/multi_asic.py, tests/namespace/test_forward.py, tests/test_forward.py
For multi-asic platforms, the default route was getting retrieved from only
the last namespace as the result dictionary was being written with the same key.
To avoid this, modify implementation to retrieve default routes from all
front end asic namespaces. Update implementation to ensure that only
external routes are displayed in the result.
- Fix RouteUpdater implementation and add unit-test to test multiple namespaces.
- Fix RouteUpdater implementation to retrieve default routes from all front end asic namespaces.
- Fix implementation to ensure only external routes are displayed in the result.
- Add test case to test RFC4292 implementation for multiple namespaces scenario.
- Unit-test cases should pass.
- Update snmp docker with …
=> [RFC4292][Namespace]: Fix implementation of RouteUpdater for multi-asic platform

src/sonic_ax_impl/__main__.py
**Depends on https://github.com/Azure/sonic-swss-common/pull/418**
There are many warning messages in swsscommon. Here I set the log_level higher to ERROR, so warnings will disappear in syslog.
Fixed https://github.com/Azure/sonic-buildimage/issues/5992
=> Set swsscommon logging level

src/sonic_ax_impl/mibs/__init__.py
Signed-off-by: Stepan Blyshchak <stepanb@nvidia.com>
Fix a missed bytes to string conversion.
Remove "b"
Add a L3 VLAN interface and query SNMP RFC1213 MIB.
=> [mibs] b'VLAN_TABLE:' -> 'VLAN_TABLE'

src/sonic_ax_impl/mibs/ietf/rfc4292.py, tests/mock_tables/multi_asic.py
[RouteUpdater]: Fix multi_asic mock function implementation.
Update multi_asic mock function to return port_table from config_db
was returning empty dictionary due to which RouteUpdater class
was not completely unit-tested as one of the condition check was
never set to true.
1. Fix multi_asic mock function implementation to get port_table information.  There was a mistake in mock_get_port_table function due to which port_table was always empty dictionary.
2. Use multi_asic.get_port_table_for_asic() function as we require port_table only of a specific namespace and do not require the entire port_table.
3. Fix the incorrect multi_asic variable name used in RouteUdpater.
Provides fix for …
=> [RouteUpdater]: Fix multi_asic mock function implementation and multi_asic variable name

src/sonic_ax_impl/main.py, src/sonic_ax_impl/mibs/ietf/rfc1213.py, tests/mock_tables/config_db.json, tests/mock_tables/global_db/config_db.json, tests/namespace/test_sysname.py, tests/test_sysname.py
[sysName]: Add sysName OID implementation in snmpagent.
sysName OID is currently supported by snmpd. Override this
implementation to make sure the latest hostname is taken
from config db.
Add sysName OID implementation in snmpagent as mentioned in https://github.com/Azure/sonic-snmpagent/issues/170
- Add a new MIB class to support retrieving sysName from config_db
- Add unit-test to test sysName OID.
Bring up snmp docker with the changes.
Configure  a new hostname using "config hostname <>" command.
Execute SNMP query to get 1.3.6.1.2.1.1.5.0, ensure new configured hostname is retrieved.
```
Testing result on sonic-vs platform:
admin@vlab-01:~$ sudo config hostname test …
```
=> [sysName]: Implement sysName OID

src/sonic_ax_impl/mibs/ieee802_1ab.py
We notice sometimes an error message. This PR will handle the case when the specific Redis table is not available/empty.
```
Jan  1 23:11:19.144294 vlab-01 ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/ax_interface/mib.py", line 37, in start
self.reinit_data()
File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/ieee802_1ab.py", line 115, in reinit_data
self.loc_chassis_data['lldp_loc_sys_cap_supported'] = parse_sys_capability(self.loc_chassis_data['lldp_loc_sys_cap_supported'])
KeyError: 'lldp_loc_sys_cap_supported'
```
Unit test
=> Fix: handle empty LOC_CHASSIS_TABLE

src/sonic_ax_impl/mibs/ietf/physical_entity_sub_oid_generator.py, src/sonic_ax_impl/mibs/ietf/rfc2737.py, src/sonic_ax_impl/mibs/ietf/rfc3433.py, src/sonic_ax_impl/mibs/ietf/transceiver_sensor_data.py, tests/namespace/test_sensor.py, tests/test_sensor.py, tests/test_sn.py
The current snmpagent implementation hardcoded qsfp lanes to 4, but qsfp-dd has 8 lanes. In that case snmp query only display the sensors of first 4 lanes. This PR is to fix it. 
1. read actual sensor status from redis db, now we only care temperature, voltage, txpower, rxpower, txbias.
2. sort sensor data to make sure it has a solid order
3. store the data to snmpagent data structure
Manual test on master and run existing regression
=> [snmpagent] Fix hardcoded qsfp lane count by reading sensor status from DB

src/sonic_ax_impl/mibs/__init__.py, src/sonic_ax_impl/mibs/ietf/rfc2737.py, src/sonic_ax_impl/mibs/ietf/rfc3433.py, src/sonic_ax_impl/mibs/ietf/transceiver_sensor_data.py
The current snmpagent implementation hardcoded qsfp lanes to 4, but qsfp-dd has 8 lanes. In that case snmp query only display the sensors of first 4 lanes. This PR is to fix it. 
1. read actual sensor status from redis db, now we only care temperature, voltage, txpower, rxpower, txbias.
2. sort sensor data to make sure it has a solid order
3. store the data to snmpagent data structure
Manual test on 201911 and run existing regression
=> [snmpagent] [201911] Fix hardcoded qsfp lane count by reading sensor status from DB

src/sonic_ax_impl/mibs/vendor/cisco/bgp4.py
Signed-off-by: bingwang <bingwang@microsoft.com>
A 'key not found' exception will be raised in bgp4.py if the state for a given neighbor is not found in STATE_DB. 
```
ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()
#012Traceback (most recent call last):
#012  File "/usr/local/lib/python3.7/dist-packages/ax_interface/mib.py", line 43, in start
#012    self.update_data()#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/vendor/cisco/bgp4.py", line 42, in update_data
#012    state = neigh_info['state']
#012  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 345, in __getitem__
#012    return _swsscommon.FieldValueMap___getitem__(self, key)
#012IndexError: key not found …
```
=> Fix 'key not found' exception in bgp4.py

src/sonic_ax_impl/mibs/ietf/rfc2737.py
Change redis pubsub expect data type from bytes to str. There was a snmpagent framework change which transfer redis pubsub data from bytes to str, after that change, there is no need for non-framework code to do this transfer. So now we need handle str data directly.
Change data expectation from bytes to str
Run regression and manual test
=> [rfc2737] Fix issue: expect redis pubsub data to be str type instead of bytes type

src/ax_interface/util.py, src/sonic_ax_impl/mibs/ieee802_1ab.py, src/sonic_ax_impl/mibs/ietf/rfc1213.py, src/sonic_ax_impl/mibs/ietf/rfc4292.py, src/sonic_ax_impl/mibs/vendor/cisco/bgp4.py, tests/mock_tables/appl_db.json, tests/mock_tables/asic0/appl_db.json, tests/mock_tables/asic1/appl_db.json, tests/mock_tables/asic2/appl_db.json, tests/namespace/test_lldp.py, tests/test_lldp.py
Why I did:
- Fixes:-
https://github.com/Azure/sonic-buildimage/issues/7036
https://github.com/Azure/sonic-buildimage/issues/6636
- Updated to use prefix of 16 byte instead of 6 byte for Ipv6 Management Address. Confirmed with other Vendor Nos
- Fixed `lookup()` so that get-next work correctly from test-cases.
- Updated all files to use new utility API  `ip2byte_tuple()`
How I did:
- Loop through all valid and unique management ip  address associated 
with remote lldp interface and append to the the oid key list.
- Removed some of utility API as they were not being used.
How I verify:
- Extend Unit test case to cover all possible combination of management ip address
- Verify the snmpwalk when both v4 and v6 address are present
```
admin@str-sxxxx-on-2:~$ redis-cli -n 0
127.0.0.1:6379> …
```
=> Updated lldpRemManAddrTable to use all the management ip address associated with interface.

src/sonic_ax_impl/mibs/ietf/rfc4363.py
Mellanox has collected some FDBs on default VLAN, but the VLAN entry has no attributes, so it trigger this syslog message.
=> Temporarily lower the logging level for invalid FDB, which is a known issue on Mellanox

src/sonic_ax_impl/mibs/ietf/rfc2737.py, tests/mock_tables/state_db.json, tests/test_sn.py
The ideas of this MIB is to reflect the physical entities and should not be affected by the config_db.json interface configuration.
In the case where the interface does not exist (not configured at all or as a result of user removing the interface from the config_db.json due to port breakout limitation on some platforms),  entPhysicalDescr OID should return the transceiver type only and without the interface alias and the extra 'for ' text.
Signed-off-by: liora <liora@nvidia.com>
In the case interface not configured but transceiver exist, the transceiver description is only the transceiver type without the extra 'for xxx' text.
Verify if interface is configured. If yes, add to the transceiver type the interface alias. Else, only the transceiver type. …
=> [SNMP] Update description of entPhysicalDescr oid

src/sonic_ax_impl/mibs/__init__.py, tests/mock_tables/dbconnector.py
Update snmpagent to use SonicDBConfig from swsscommon.
- Update import of SonicDBConfig 
- init_namespace_dbs should return list of all namespace connector classes. Ensure that the list ordering is maintained such that the first element of the list is of the default namespace.
Tested on single asic VS; SNMP service starts without any error log.
Execute snmpwalk on one of the OIDs:
admin@vlab-01:~$ docker exec -it snmp snmpwalk -v2c -c public 127.0.0.1 iso.3.6.1.2.1.2.2.1.2
iso.3.6.1.2.1.2.2.1.2.1 = STRING: "fortyGigE0/0"
iso.3.6.1.2.1.2.2.1.2.5 = STRING: "fortyGigE0/4"
iso.3.6.1.2.1.2.2.1.2.9 = STRING: "fortyGigE0/8"
iso.3.6.1.2.1.2.2.1.2.13 = STRING: "fortyGigE0/12" …
=> [multi-asic]: Udpate to use SonicDBConfig from swsscommon

azure-pipelines.yml
fix python gcov warning "Please install dotnet core to enable automatic generation of Html report"
install dotnet core
=> Install dotnet core to fix python gcov warning for code covery color bar showing

src/sonic_ax_impl/mibs/ietf/rfc2863.py, tests/namespace/test_interfaces.py, tests/test_interfaces.py
This is a correction of https://github.com/Azure/sonic-snmpagent/pull/218, which is contained in https://github.com/Azure/sonic-buildimage/pull/7859, after community decided that entries under .1.3.6.1.2.1.31.1.1.1.18 OID should return the "description" field of PORT_TABLE entries in APPL_DB or CONFIG_DB.  For vlan, management and LAG, these are empty strings.
Deleted the lines of code quoted by Suvarna in the above PRs.  This necessitated modifying 4 unit tests that had been written under the assumption that these OIDs would return non-empty data.
Run unit tests in build and snmp tests in sonic-mgmt.
Entries under .1.3.6.1.2.1.31.1.1.1.18 OID should return the "description" field of PORT_TABLE …
=> Entries under .1.3.6.1.2.1.31.1.1.1.18 OID should return the "description" field of PORT_TABLE entries in APPL_DB or CONFIG_DB

src/sonic_ax_impl/mibs/ietf/rfc1213.py, src/sonic_ax_impl/mibs/ietf/rfc4292.py
Fixes https://github.com/Azure/sonic-buildimage/issues/8140
ref: swsssdk implementation returns None, and the library will be deprecated
libswsscommon implementation returns empty dict
Relax the condition check to accept both representations
Unit test
=> Fix: SonicV2Connector behavior change: get_all will return empty dict if the hash does not exist in Redis

src/sonic_ax_impl/mibs/ieee802_1ab.py, tests/test_lldp.py
Signed-off-by: Vivek Reddy Karri <vkarri@nvidia.com>
Fixes [#8293](https://github.com/Azure/sonic-buildimage/issues/8293)
Accumulated all the older notifications and did act only upon the latest notification discarding the others
=> CPU Spike because of redundant and flooded keyspace notifis handled

src/sonic_ax_impl/mibs/ietf/rfc1213.py
Initialize lag oid map in reinit_data instead of
updating in update_data. Updating lag oid map in update_data
can cause descrepancy as interface oid map is updated in
reinit_data.
There could be a scenario when lag oid map has lag oids updated in update_data but interfaces oid map is not updated as interfaces oid map is updated in reinit_data. When SNMP service comes up, there could be a short instance of time when interfaces oid map (oid_sai_map) is empty or not complete but lag oid map (oid_lag_name_map) is updated with lag oids and lag members. At this short span, if a SNMP query is done to get interfaces counters, current code will try to get LAG counters and will fail at https://github.com/Azure/sonic-snmpagent/blob/master/src/sonic_ax_impl/mibs/ietf/rfc1213.py#L383 …
=> [RFC1213]: Initialize lag oid map in reinit_data

src/sonic_ax_impl/mibs/ietf/rfc1213.py
updating in update_data. Updating lag oid map in update_data
can cause descrepancy as interface oid map is updated in
reinit_data.
Same change as: #232 for 201911 branch.
=> [201911][RFC1213]: Initialize lag oid map in reinit_data

src/sonic_ax_impl/mibs/ietf/rfc1213.py
Same change as: https://github.com/Azure/sonic-snmpagent/pull/232 for 201811 branch.
=> [201811][RFC1213]: Initialize lag oid map in reinit_data

src/sonic_ax_impl/mibs/__init__.py
Modified init_sync_d_interface_tables() to support the VoQ Inband interface Ethernet-IB port name
This commit depends on --  https://github.com/Azure/sonic-py-swsssdk/pull/113 which create the Inband index and name mapping
=> [Voq][Inband] Support the Ethernet-IB port

src/sonic_ax_impl/mibs/__init__.py, src/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py, tests/test_mibs.py
subagent comes up. Do not flag runtime error if queue stat
counter is not found in the first 3 update iterations.
Ideally SNMP service starts only after swss/syncd comes up.
But due to timing of bring up, It could happen that SNMP is trying to retrieve queue stat counter before it is update by syncd.
This is only seen once when the SNMP service comes up, as from the next iteration, syncd has updated the queue stats and it is available for SNMP to use.
ERR snmp#snmp-subagent [sonic_ax_impl] ERROR: No queue stat counters found in the Counter DB. SyncD database is incoherent.
This message is seen only once in all the cases observed, which means that once the counters are populated, snmp is able to retrieve the …
=> Fix Queue stat unavailable error seen during SNMP service start

src/sonic_ax_impl/mibs/ietf/rfc2737.py, tests/mock_tables/dbconnector.py, tests/mock_tables/state_db.json, tests/test_sn.py
data.
If there is an issue in transceiver data and some junk characters are present in transceiver data, then SNMP does not parse this information and transceiver MIB cannot be queried.
Error seen in such scenario:
```
show interface transceiver eeprom
...
Ethernet5: SFP EEPROM detected
Connector: Unknown
Encoding: Unknown
Extended Identifier: Unknown
Extended RateSelect Compliance: Unknown
Identifier: Unknown
Length Cable Assembly(m): 255
Length OM1(m): 255
Length OM2(m): 255
Length OM3(2m): 255
Length(km): 255
Nominal Bit Rate(100Mbs): 255
Specification compliance:
10/40G Ethernet Compliance Code: 10GBase-LR
Fibre Channel Speed: 100 Mbytes/Sec
Fibre Channel link length/Transmitter Technology: AAA
Fibre Channel …
```
=> [rfc2737]: Handle unicode error when parsing transceiver

src/sonic_ax_impl/mibs/ietf/rfc1213.py
A KeyError exception raised in rfc1213.py if LAG port don't have L3 interface
````
Oct 25 14:10:29.864852 sonic ERR snmp#snmp-subagent [ax_interface] ERROR: SubtreeMIBEntry.__call__() caught an unexpected exception during _callable_.__call__()
#012Traceback (most recent call last):
#012  File "/usr/local/lib/python3.7/dist-packages/ax_interface/mib.py", line 194, in __call__
#012    return self._callable_.__call__(sub_id, *self._callable_args)
#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/ietf/rfc1213.py", line 413, in get_counter
#012    sai_lag_rif_id = self.port_rif_map[sai_lag_id]#012KeyError: '20000000007c2'
````
Checked if sai_lag_id is contained in port_rif_map
Build docker-snmp. No exception is …
=> Fix: LAG counters, if LAG don't have L3 interface

src/sonic_ax_impl/mibs/ieee802_1ab.py
Fix sonic_ax_impl memory leak in LLDPLocManAddrUpdater.
In LLDPLocManAddrUpdater.reinit_data(), reset man_addr_list to empty list before append new data.
Pass all UT.
Manually check there is no memory leak.
Fix sonic_ax_impl memory leak in LLDPLocManAddrUpdater.
=> [201811] Fix sonic_ax_impl memory leak in LLDPLocManAddrUpdater.

src/sonic_ax_impl/mibs/ietf/rfc2737.py, src/sonic_ax_impl/mibs/ietf/rfc3433.py, tests/mock_tables/state_db.json, tests/test_sensor.py, tests/test_sn.py
RJ45 port will expose the below info to STATE_DB, since there is NO embedded sensor on RJ45 ports, so Entity MIB and Entity sensor MIB should skip the  TRANSCEIVER_INFO and TRANSCEIVER_DOM_SENSOR DB entries for RJ45 ports.
```
"TRANSCEIVER_INFO|Ethernet2": {
"type": "RJ45",
"vendor_rev": "N/A",
"serial": "N/A",
"manufacturer": "N/A",
"model": "N/A",
"is_replaceable": "N/A"
},
"TRANSCEIVER_DOM_SENSOR|Ethernet2": {
"temperature": "N/A",
"voltage": "N/A",
"tx1bias": "N/A",
"tx2bias": "N/A",
"tx3bias": "N/A",
"tx4bias": "N/A",
"rx1power": "N/A",
"rx2power": "N/A",
"rx3power": "N/A",
"rx4power": "N/A",
"tx1power": "N/A",
"tx2power": "N/A",
"tx3power": "N/A",
"tx4power": "N/A"
}
```
Add logic to detect the type of transceiver, skip RJ45 type.
**- How to …
=> [RFC2737, RFC3433] Exclude RJ45 port from Entity MIB and Entity sensor MIB

src/sonic_ax_impl/mibs/__init__.py, tests/test_mibs.py
cherrypick of: https://github.com/Azure/sonic-snmpagent/pull/246
fixes https://github.com/Azure/sonic-buildimage/issues/9996
Handle error seen on system where vlan interface map is not present.
This change requires: https://github.com/Azure/sonic-py-swsssdk/pull/117
On chassis platform, on supervisor there are not ports available in config_db. So, there is no vlan interface map in counters db, which causes this error in syslog:
```
ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.7/dist-packages/ax_interface/mib.py", line 37, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/ietf/rfc1213.py", line 233, in …
```
=> [202111] Handle error seen on system where vlan interface map is not present

src/sonic_ax_impl/mibs/__init__.py, src/sonic_ax_impl/mibs/ietf/rfc1213.py, src/sonic_ax_impl/mibs/ietf/rfc4363.py
In a dynamic environment, it is possible that some of the keys may
disappear between invoking keys() and get_all().
Prevent unnecessary timeout of blocking get_all().
=> Fix: not to use blocking get_all() after keys()

src/sonic_ax_impl/mibs/ietf/rfc4363.py
Follow up https://github.com/Azure/sonic-snmpagent/pull/255.
If route change too fast between keys/hgetall, the original implementation will throw exception and lead to ERR in syslog.
=> Fix: if routestr does not exist, skip

src/sonic_ax_impl/mibs/ietf/rfc1213.py, src/sonic_ax_impl/mibs/ietf/rfc4363.py
Manual cherry-pick below commits and resolve conflicts.
1477c36 2022-05-04 | Fix: if routestr does not exist, skip (#257) [Qi Luo]
57f1af6 2022-05-02 | Fix: not to use blocking get_all() after keys() (#255) [Qi Luo]
=> [201811] Fix: not to use blocking get_all() after keys(), if routestr does not exist, skip

src/ax_interface/mib.py
Fix an error raised in snmp container stop path. The issue is seen when SIGTERM is send to SNMP supervisord, and it attepmts to stop `snmp-subagent`.
There is a bug in subagent's shutdown path where below erros is seen upon receiving SIGTERM:
```
ERROR: Uncaught exception in sonic_ax_impl.main#012Traceback (most recent call last):#012  
File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/main.py", line 72, in main#012
event_loop.run_until_complete(agent.run_in_event_loop())#012  
File "/usr/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete#012
return future.result()#012  
File "/usr/local/lib/python3.6/dist-packages/ax_interface/agent.py", line 49, in run_in_event_loop#012
await asyncio.wait_for(background_task, BACKGROUND_WAIT_TIMEOUT, …
```
=> [201911] Fix snmp subagent errors in shutdown path

setup.py
Update setup.py to remove python .whl package dependency to swsssdk.
Update setup.py and remove dependency.
Pass all UT.
Update setup.py to remove python .whl package dependency to swsssdk.
=> Remove python .whl package dependency to swsssdk

tests/mock_tables/asic0/database_config.json, tests/mock_tables/asic1/database_config.json, tests/mock_tables/asic2/database_config.json, tests/mock_tables/database_config.json, tests/mock_tables/global_db/database_config.json
This PR is part of the following HLD:
Persistent loglevel HLD: https://github.com/sonic-net/SONiC/pull/1041
Deleted the LOGLEVEL_DB.
After the Logger tables moved from the LOGLEVEL_DB to the CONFIG_DB and the jinja2_cache was deleted the LOGLEVEL_DB is not in use.
Removed the LOGLEVEL_DB from the SONiC code
All tests were passed
=> Remove LOGLEVEL DB since is no longer used

src/sonic_ax_impl/mibs/ietf/rfc4363.py
It is considered normal that the dependences of FDB_ENTRY are temporarily not available.
=> Remove error logging on "failed in fdb_vlanmac"

azure-pipelines.yml
Fix pipeline no enough disk space to download artifact issue.
Microsoft ADO (number only): 24624663
Fix pipeline no enough disk space to download artifact issue.
Improve pipeline to only download *.deb and *.whl 
Pass all UT
Fix pipeline no enough disk space to download artifact issue.
=> Fix pipeline no enough disk space to download artifact issue

.github/workflows/semgrep.yml, src/sonic_ax_impl/mibs/ietf/rfc4363.py, tests/test_rfc4363.py
Fix FdbUpdater crash when SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID attribute missing.
Microsoft ADO (number only): 16189251
Fix FdbUpdater crash when SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID attribute missing.
Add try-catch block in rfc3463 FdbUpdater
Manually test.
Pass all UT
Fix FdbUpdater crash when SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID attribute missing.
=> Fix FdbUpdater crash when SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID attribute missing.

src/sonic_ax_impl/mibs/ietf/rfc3433.py, tests/test_rfc3433.py
Fix PhysicalSensorTableMIBUpdater crash when 'type' attribute missing.
Microsoft ADO (number only): 24869277
Fix PhysicalSensorTableMIBUpdater crash when 'type' attribute missing.
Check 'type' attribute, if missing write error log in PhysicalSensorTableMIBUpdater.
Manually test.
Pass all UT
Fix PhysicalSensorTableMIBUpdater crash when 'type' attribute missing.
=> Fix key missing exception when invalied transiver info in STATE_DB

src/sonic_ax_impl/mibs/ietf/rfc2863.py, tests/mock_tables/appl_db.json, tests/test_hc_interfaces.py
This change makes SNMP report the correct interface speed for PortChannels instead of defaulting to 40G.
Similar to `intfutil`, the code simply sums up the interface speeds of all member ports. The logic for iterating over members is based on `_get_counter`.
- Check `snmpwalk -v 2c -c public <IP> ifHighSpeed`, note that PortChannels are reported as 40G
- Apply the change
- Check again, note that the same speed as in `show interface status` is reported now.
Support reporting interface speeds for PortChannels through SNMP
=> Support interface speed for PortChannels

azure-pipelines.yml
Fix pipeline build break caused by libhredis remove from sonic-buildimage artifect.
Pipeline build break because sonic-buildimage repo not build libhredis by this PR: https://github.com/sonic-net/sonic-buildimage/pull/15633
Fix pipeline build break caused by libhredis remove from sonic-buildimage artifect.
Install libhiredis0.14 from debian apt source.
Pass all UT
Fix pipeline build break caused by libhredis remove from sonic-buildimage artifect.
=> Fix pipeline build break caused by libhredis remove from sonic-buildimage artifect. 

tests/test_rfc2863.py
Add unit test for IfHighSpeed with PortChannel with no member ports
Microsoft ADO (number only): 25199873
Add new UT cover InterfaceMIBUpdater.get_high_speed(), this will fix issue: https://github.com/sonic-net/sonic-snmpagent/issues/294
Add new UT and mock data to test InterfaceMIBUpdater.get_high_speed() with PortChannel with no member ports
Pass all UT
Add unit test of IfHighSpeed with PortChannel with no member ports
=> Add unit test for IfHighSpeed with PortChannel with no member ports

tests/test_rfc2863.py
Fix IfHighSpeed UT issue on 202012
Microsoft ADO (number only): 25199873
Fix IfHighSpeed UT issue on 202012
Fix UT backport issue by remove unnecessary mock data.
Pass all UT
Fix IfHighSpeed UT issue on 202012
=> [202012] Fix IfHighSpeed UT issue on 202012

src/sonic_ax_impl/mibs/ietf/rfc2863.py, tests/test_rfc2863.py
Fix IfHighSpeed UT issue on 201911
Microsoft ADO (number only): 25199873
Fix IfHighSpeed UT issue on 201911
Fix UT backport issue by change string to binary, which caused by this change in 202012:
https://github.com/liuh-80/sonic-snmpagent/commit/57e54d9561934b853a44185bbb401207f4503292#diff-8b42be2a8bea9f0ba1ac57afd853dc86afbdb80a8e31b959278b041b71431119
Pass all UT
Fix IfHighSpeed UT issue on 201911
=> [201911] Fix IfHighSpeed UT issue on 201911

src/ax_interface/mib.py, src/sonic_ax_impl/mibs/ietf/rfc1213.py, src/sonic_ax_impl/mibs/ietf/rfc2737.py, src/sonic_ax_impl/mibs/ietf/rfc2863.py, src/sonic_ax_impl/mibs/ietf/rfc3433.py, src/sonic_ax_impl/mibs/ietf/rfc4292.py, src/sonic_ax_impl/mibs/ietf/rfc4363.py, src/sonic_ax_impl/mibs/vendor/cisco/ciscoPfcExtMIB.py, src/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py, tests/test_rfc1213.py, tests/test_rfc3433.py, tests/test_rfc4292.py, tests/test_rfc4363.py
Improve MIBUpdater to re-connect DBConnector when re-init data.
Microsoft ADO (number only): 24705208
Fix when redis restart, some MIBUpdater's db connection will broken and keeps report error to syslog issue.
There will be following message repeat in syslog:
```
#012  File "/usr/local/lib/python3.7/dist-packages/sonic_ax_impl/mibs/ietf/rfc2737.py", line 674, in _update_per_namespace_data#
#012    msg = pubsub.get_message()#
#012  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1626, in get_message#
#012    return _swsscommon.PubSub_get_message(self, timeout)#
#012RuntimeError: RedisError: Failed to select, err=3: errstr=Server closed the connection
```
Re-connect DBConnector in every MIBUpdater's reinit_data method.
**- How to …
=> Improve MIBUpdater to re-connect DBConnector when re-init data.

src/sonic_ax_impl/__init__.py
Enable faulthandler to provide more fault information.
Microsoft ADO (number only): 17637258
Enable faulthandler to provide more fault information.
Enable faulthandler when snmp-subagent startup.
Pass all UT
Enable faulthandler to provide more fault information.
=> Enable faulthandler to provide more fault information.

src/ax_interface/agent.py, src/ax_interface/mib.py, src/ax_interface/protocol.py, tests/test_agent.py
remove loop argument from asyncio APIs
=> snmp-subagent changes for bookworm upgrade

azure-pipelines.yml
Modify path of python-wheels package to use bookworm.
Seeing the below errors in azure pipeline:
```
WARNING: Requirement '../target/python-wheels/buster/swsssdk*-py3-*.whl' looks like a filename, but the file does not exist
ERROR: swsssdk*-py3-*.whl is not a valid wheel filename.
```
Modify path of python-wheels package to use bookworm
=> Modify path of python-wheels package to use bookworm

src/sonic_ax_impl/mibs/vendor/cisco/ciscoPfcExtMIB.py, tests/namespace/test_pfc.py
When querying for PFC counters MIB cpfcIfTable if there is no interface present on the device, then there is an exception while handing get_next as the implementation tries to return the first index of an empty list.
This happens in case of VoQ chassis Supervisor where there are no interfaces present. 
Anytime a snmp query is made to cpfcIfTable 1.3.6.1.4.1.9.9.813.1.1, the exception message gets logged on the device.
Currently if sub_id is None, if_range[0] is returned. IF if_range is empty array this can cause an Exception.
Removed this check to avoid returning if_range[0].
The check "if not sub_id" is not required here.
right = bisect_right(self.if_range, sub_id) will handle if the sub_id is empty or if the if_range is empty by returning 0 index.
**- …
=> [ciscoPfcExtMIB]: Remove returning first intf index if subid is empty

.gitignore, src/ax_interface/mib.py, src/sonic_ax_impl/mibs/__init__.py, src/sonic_ax_impl/mibs/ietf/rfc2737.py, tests/mock_tables/dbconnector.py, tests/test_rfc1213.py, tests/test_rfc2737.py
Fixes the redis memory leak bug:
https://github.com/sonic-net/sonic-snmpagent/issues/342
There's chance that the physical_entity_updater creates subscriptions to redis, and never consume the messages due to exceptions.
Then the memory buffer(omem) of redis client starts to increase and never end, redis memory leaks.
The reason is all 5 physical entity cache updaters inherit from PhysicalEntityCacheUpdater.
In the first update_data, they initialize the psubscription to redis database.
https://github.com/sonic-net/sonic-snmpagent/blob/c5301b2cf94304deb8e09959d67af6a089155507/src/sonic_ax_impl/mibs/ietf/rfc2737.py#L667
And everytime when the update_data is called again, it get the message from the psub and process.
https://github.com/sonic-net/sonic-snmpagent/blob/c5301b2cf94 …
=> Fix redis memory leak issue in PhysicalEntityCacheUpdater

src/ax_interface/agent.py, src/ax_interface/constants.py, src/ax_interface/mib.py, src/ax_interface/util.py, src/sonic_ax_impl/__main__.py, src/sonic_ax_impl/main.py, src/sonic_ax_impl/utils/arg_parser.py, tests/test_agent.py, tests/test_arg_parser.py, tests/test_utils.py
Fix https://github.com/sonic-net/sonic-buildimage/issues/21314
The SNMP agent and MIB updaters are basic on Asyncio/Coroutine,
the mib updaters share the same Asyncio event loop with the SNMP agent client.
Hence during the updaters executing, the agent client can't receive/respond to new requests.
When the CPU utilization is high (In some stress test we make CPU 100% utilization), the updates are slow, and this causes the snmpd request to be timeout because the agent got suspended during updating.
Decrease the MIB update frequency when the update execution is slow.
pros:
1.  The snmp request can success even if 100% CPU utilization.
2. The snmpd request seldomly fails due to timeout, combined with https://github.com/sonic-net/sonic-buildimage/pull/21316 , we have 4*5 = …
=> Fix snmp agent not-responding issue when high CPU utilization

src/sonic_ax_impl/mibs/__init__.py, src/sonic_ax_impl/mibs/ietf/physical_entity_sub_oid_generator.py, src/sonic_ax_impl/mibs/ietf/rfc2737.py, src/sonic_ax_impl/mibs/ietf/rfc3433.py, tests/test_rfc2737.py, tests/test_rfc3433.py
With Modular Chassis, fans need not be present just in the fan drawers, but also
in fabric modules. Currently, fan and sensor information of fabric modules is
not accessible via SNMP. This patch set fixes that problem.
Essentially, make fans under fabric modules accessible in a way we currently
access fans under fan drawers.
Added a new cache updater, which keeps track of all the fans under fabric modules,
so that they can be queried via SNMP.
SNMP walk of chassis should display the fan information, if any, present under fabric
modules.
Added a unit test and also tested these changes manually on Internal machines.
Other PR's of interest for this change: …
=> snmpagent: modify entities to include fans under fabric module

src/sonic_ax_impl/mibs/ietf/rfc1213.py, tests/test_rfc1213.py
Fix to handle error seen:
```
ERR snmp#snmp-subagent [ax_interface] ERROR: SubtreeMIBEntry.__call__() caught an unexpected exception during _callable_.__call__()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.11/dist-packages/ax_interface/mib.py", line 248, in __call__#012    return self._callable_.__call__(sub_id, *self._callable_args)#012           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^#012  File "/usr/local/lib/python3.11/dist-packages/sonic_ax_impl/mibs/ietf/rfc1213.py", line 414, in get_counter#012    counter_value += self._get_counter(mibs.get_index_from_str(lag_member), table_name)#012TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```
Above error can be seen if certain COUNTER is not supported in …
=> [rfc1213] Handle error seen when interface counter is not available in COUNTERS_DB
