sonic-net/sonic-snmpagent

src/sonic_ax_impl/__main__.py
src/sonic_ax_impl/mibs/__init__.py

Related to Azure/SONiC#51
Trying to solve in below steps:
- [sonic-py-swsssdk](https://github.com/Azure/sonic-py-swsssdk/pull/3)
- sonic-snmpagent

sonic_ax_impl supports redis connection options

---

README.md
setup.py
src/sonic_ax_impl/__main__.py
src/sonic_ax_impl/mibs/__init__.py
tests/mock_tables/dbconnector.py

Update to work with https://github.com/Azure/sonic-py-swsssdk/pull/4

Update nomenclature: 'sswsdk' -> 'swsssdk'

---

src/sonic_ax_impl/mibs/__init__.py

Signed-off-by: Shu0T1an ChenG <shuche@microsoft.com>

[mibs]: Fix bug module has no attribute 'get_index_from_str'

---

src/sonic_ax_impl/main.py
src/sonic_ax_impl/mibs/ietf/rfc2737.py

- Add support of entPhysicalClass MIB.
- Add support of entPhysicalSerialNum MIB.

[mibs]: Add support of RFC 2737 MIBs.

---

src/sonic_ax_impl/mibs/ietf/rfc4363.py

Follow up with old PR: https://github.com/Azure/sonic-snmpagent/pull/37

Remove unused code

---

src/sonic_ax_impl/mibs/ietf/rfc4292.py

Signed-off-by: Qi Luo <qiluo-msft@users.noreply.github.com>

Fix ipCidrRouteStatus for loopback: no need to check route table

---

src/sonic_ax_impl/mibs/ietf/rfc2737.py
tests/mock_tables/dbconnector.py
tests/mock_tables/state_db.json
tests/test_sn.py

And add the missing unit test for PhysicalTableMIB

 Fix entPhysicalSerialNum OID

---

README.md
src/sonic_ax_impl/main.py
src/sonic_ax_impl/mibs/__init__.py
src/sonic_ax_impl/mibs/ietf/rfc2737.py
src/sonic_ax_impl/mibs/ietf/rfc3433.py
tests/mock_tables/state_db.json
tests/test_sensor.py
tests/test_sn.py

Signed-off-by: Stepan Blyschak <stepanb@mellanox.com>

Extend RFC 2737 MIB and implement RFC 3433

---

src/sonic_ax_impl/mibs/ietf/rfc2863.py
tests/mock_tables/appl_db.json
tests/test_hc_interfaces.py

* ifAlias should return the interface description not the
SONiC name
* unit tests
Signed-off-by: michel.moriniaux@gmail.com

sonic-snmpagent: fixed interface descriptions

---

src/sonic_ax_impl/mibs/ietf/rfc1213.py
src/sonic_ax_impl/mibs/ietf/rfc2863.py
tests/mock_tables/appl_db.json
tests/test_hc_interfaces.py
tests/test_interfaces.py

following ifspeed PR I introduced a bug:
line 353 should read return min(self.RFC1213_MAX_SPEED, speed * 1000000)
self. was missing

Error on line 353 of rfc1213.py

---

src/sonic_ax_impl/mibs/ietf/rfc3433.py

Submit this PR as Stepan Blyschak

Fix rfc3433 unit test

---

src/sonic_ax_impl/mibs/ieee802_1ab.py

fixes #79 
Added handling of case when some "LOC_CHASSIS" data is absent in APP DB.
Added a check if we received something from the DB.
Fix snmpagent issue: AttributeError: 'NoneType' object has no attribute 'decode'

[lldp] fix issue #79 - AttributeError: 'NoneType' object has no attribute 'decode'

---

src/sonic_ax_impl/mibs/vendor/cisco/ciscoEntityFruControlMIB.py

Signed-off-by: Shu0T1an ChenG <shuche@microsoft.com>

Fix NameError: name 'logger' is not defined bug

---

src/sonic_ax_impl/mibs/ietf/rfc4363.py

When SONiC system get a few hundreds MACs learnt on vlans, snmp-subagent
started to see below errors:
INFO supervisord: snmp-subagent socket.send() raised exception.
ERR snmp-subagent [ax_interface] ERROR: [Errno 32] Broken pipe
This was due to the snmpd getting timeout from subagent and closed the socket.
It was root caused to be the mac polling algorithm inefficiency.
The redis-server was taking average > 60% CPU cycles (peak to 85~90%) of one core.
After the fix in this commit, the redis-server load is average to
~3% (peak to ~6%) of one core.
Signed-off-by: Zhenggen Xu <zxu@linkedin.com>
The snmpd timeout value can be configured also, see here:
http://www.net-snmp.org/docs/man/snmpd.conf.html
agentXTimeout NUM
defines the timeout period (NUM seconds) for an AgentX request. Default is …

Fix snmp mac polling performance issue.

---

src/sonic_ax_impl/mibs/ietf/rfc4292.py
tests/mock_tables/appl_db.json

Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>
fixes #93 
Get rid of mask when getting the lo ip from APP DB.
snmpwalk -v 2c -c public sonic-dut   1.3.6.1.2.1.4.24.4.1.1
fix loopback ip parsing mask issue

[rfc4292] fix loip mask issue

---

src/sonic_ax_impl/mibs/ietf/rfc2737.py

Signed-off-by: Stepan Blyschak <stepanb@mellanox.com>

[rfc2737] fix typo in xcvr removal flow

---

src/sonic_ax_impl/mibs/ieee802_1ab.py

Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>
Fixed an issue, when the lldp_loc_mgmt_ip was unavailable in APP DB (at startup for example),
the reinit_data resulted in an ERR log:
```
ERR snmp#snmp-subagent [sonic_ax_impl] ERROR: Invalid local mgmt IP
```
With the fix, we will warn the user and return. In most cases the data will soon appear in DB. In other cases we get a warning every reinit_data(1m).
stop lldp, snmp services
Flush LLDP_LOC_CHASSIS from  APPDB,
start snmp service

[LLDP MIB] fix lldp loc mgmt ip logic

---

tests/mock_tables/dbconnector.py

Remove repeated code
Remove unused import

Simplify test code

---

setup.py

pin psutil version to 5.7.0
fix build failure. build to make sure it works.

[psutil] pin psutil version to 5.7.0

---

src/sonic_ax_impl/mibs/__init__.py
src/sonic_ax_impl/mibs/ieee802_1ab.py
src/sonic_ax_impl/mibs/ietf/rfc1213.py
src/sonic_ax_impl/mibs/ietf/rfc2737.py
src/sonic_ax_impl/mibs/ietf/rfc2863.py
src/sonic_ax_impl/mibs/ietf/rfc3433.py
src/sonic_ax_impl/mibs/ietf/rfc4292.py
src/sonic_ax_impl/mibs/ietf/rfc4363.py
src/sonic_ax_impl/mibs/vendor/cisco/bgp4.py
src/sonic_ax_impl/mibs/vendor/cisco/ciscoEntityFruControlMIB.py
src/sonic_ax_impl/mibs/vendor/cisco/ciscoPfcExtMIB.py
src/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py
tests/mock_tables/dbconnector.py
tests/namespace/test_lldp.py
tests/namespace/test_mibs.py
tests/test_lldp.py
tests/test_mibs.py

This is the following steps to migrate to SonicV2Connector with `decode_responses=True`
Please check the plan in https://github.com/Azure/sonic-py-swsssdk/pull/89
Unit test and DUT test.

Interact with Redis by str instead of bytes, migrate to SonicV2Connector with `decode_responses=True`

---

tests/mock_tables/dbconnector.py

The original code only works on `str` value

Improve MockRedis _encode(): so it will work on all types of value

---

src/sonic_ax_impl/mibs/ietf/rfc1213.py

Counter values were stored as a mix of strings and ints.
This caused swsscommon to fail when there is an attempt
to write integer value where strings value was stored.
Signed-off-by: Stepan Blyshchak <stepanb@nvidia.com>

[rfc1213] fix counter value type.

---

src/sonic_ax_impl/mibs/ietf/rfc4363.py

Fix fdb_vlanmac() on corner cases
Existing unit test

Fix fdb_vlanmac() on corner cases

---

src/sonic_ax_impl/bin/sysDescr_pass.py

Signed-off-by: Guohan Lu <lguohan@gmail.com>
let sysDescr_pass use python3
tested on master image

let sysDescr_pass use python3

---

azure-pipelines.yml

[CI] Setup dummy azure pipeline

---

azure-pipelines.yml
pytest.ini

Signed-off-by: Guohan Lu <lguohan@gmail.com>
test results
https://dev.azure.com/mssonic/build/_build/results?buildId=9572&view=ms.vss-test-web.build-test-results-tab

[ci]: setup proper azp

---

azure-pipelines.yml

Modify path of python wheels to be installed as per changes in sonic-buildimage repo.
Modify path of swsssdk and sonic-py-common python wheels.

Modify path of python wheels to be installed.

---

azure-pipelines.yml

Support code diff coverage, and set threshold to 50%

[ci]: Support code diff coverage

---

azure-pipelines.yml

Use a more stable build pipeline for artifact dependencies
Use Azure.sonic-buildimage.official.vs pipeline as artifact source

[build] use Azure.sonic-buildimage.official.vs pipeline as artifact source

---

azure-pipelines.yml

To enable PR checkers for 202111 PRs.

[ci] add pr trigger for 202111 branch

---

azure-pipelines.yml

Change code diff coverage threshold to 80%
Change code diff coverage threshold to 80%
Manually check the config file.
Change code diff coverage threshold to 80%

[ci]: Change diff coverage threshold to 80% 

---

src/sonic_ax_impl/mibs/ietf/rfc1213.py
src/sonic_ax_impl/mibs/ietf/rfc4292.py
tests/test_rfc1213.py
tests/test_rfc4292.py

Fix: zero route may have empty nexthop. Improve code robustness.
Manual test:
1. manipulate ApplDB default route: remove nexthop field and value
2. recover
3. manipulate ApplDB default route: remove ifname field and value
4. recover
Also add unit test.

Fix: zero route may have empty nexthop

---

azure-pipelines.yml

For the code coverage HTML files, it looks like .NET 6.0 or newer is now required. Upgrade to .NET 8.0 to get ahead of this.

Update dotnet version installed to 8.0
